apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crisisiq
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  tls:
    - hosts:
        - crisisiq.example.com
      secretName: crisisiq-tls
  rules:
    - host: crisisiq.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: crisisiq-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crisisiq-frontend
                port:
                  number: 3000
